#!/usr/bin/env python3
"""Generate compile-time preparedness defaults from authoritative baseline data."""
from pathlib import Path
import yaml

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "data/common/baseline.yaml"
TARGET = ROOT / "internal/baseline/generated.go"

with SOURCE.open(encoding="utf-8") as f:
    data = yaml.safe_load(f)
water = data["jurisdiction_overrides"]["NO"]["water"]
if water.get("status") != "authoritative":
    raise SystemExit("NO water baseline is not authoritative")
weekly = water["stored_litres_per_person_week"]
if not isinstance(weekly, (int, float)) or weekly <= 0:
    raise SystemExit("invalid NO stored_litres_per_person_week")

content = f'''// Code generated by tools/generate_baseline_go.py; DO NOT EDIT.\npackage baseline\n\nconst NorwayStoredWaterLitresPerPersonWeek = {weekly}\nconst NorwayStoredWaterLitresPerPersonDay = float64(NorwayStoredWaterLitresPerPersonWeek) / 7\n'''
TARGET.parent.mkdir(parents=True, exist_ok=True)
TARGET.write_text(content, encoding="utf-8")
print(TARGET.relative_to(ROOT))
