// Code generated by tools/generate_baseline_go.py; DO NOT EDIT.
package baseline

const NorwayStoredWaterLitresPerPersonWeek = 20
const NorwayStoredWaterLitresPerPersonDay = float64(NorwayStoredWaterLitresPerPersonWeek) / 7
